In [1]:
import numpy as np 
import scipy.stats as ss 

#### Binomial Distribution 

In [2]:
#P(X=r)=ncr * p*r(1-p)n-r
n=10
r=4
p=0.4

In [3]:
#calculate the probability 
ss.binom.pmf(r,n,p)

0.25082265599999987

In [4]:
np.round(ss.binom.pmf(r,n,p),3)

0.251

In [5]:
#cumulative distribution 
np.round(ss.binom.cdf(r,n,p),3)

0.633

### Normal Distribution

In [6]:
#given mean and standard deviation
M=60
sd=10
x=40

In [9]:
#compute for P(X<=x)
ss.norm.cdf(x,M,sd)

0.022750131948179195

In [10]:
#compute the normal dist and then cumulative dist
ss.norm(60,10).cdf(40)

0.022750131948179195

In [11]:
ss.norm.cdf(80,60,10) -ss.norm.cdf(40,60,10)

0.9544997361036416

### Random Numbers

In [14]:
?np.random

   #### 1. Binomial distribution

In [15]:
?np.random.binomial

In [16]:
#generate radom 10 samples for the given 
n=10
p=0.4
size=10

In [17]:
np.random.binomial(n,p,size)

array([5, 8, 3, 3, 5, 4, 4, 4, 4, 5])

#### 2.Normal distribution

In [18]:
?np.random.normal

In [19]:
#given mean and sd 
M=60
sd=10

In [21]:
np.random.normal(M,sd,10)

array([62.00669816, 56.97359645, 62.12912813, 60.31510773, 54.78559368,
       74.12634993, 62.47216941, 65.5165207 , 53.44357615, 47.26047515])

#### Seed

In order to keep the output fixed we use seed 

In [22]:
?np.random.seed

In [29]:
seed=100
np.random.seed(seed)

###### The seed has to be intialised each time to get the same output

In [27]:
np.random.normal(M,sd,10)

array([42.50234527, 63.42680403, 71.53035803, 57.47563963, 69.81320787,
       65.14218841, 62.21179669, 49.29956669, 58.10504169, 62.55001444])

In [30]:
np.random.normal(M,sd,10)

array([42.50234527, 63.42680403, 71.53035803, 57.47563963, 69.81320787,
       65.14218841, 62.21179669, 49.29956669, 58.10504169, 62.55001444])

### Combinations

In [31]:
from itertools import combinations

given list containing n number of objects , we can find all combinations of size r

In [32]:
alpha ='ABCD'

In [34]:
p=combinations(alpha,3)
p

In [36]:
list(p)

[('A', 'B', 'C'), ('A', 'B', 'D'), ('A', 'C', 'D'), ('B', 'C', 'D')]

In [37]:
alpha=['A','B','C','D']

In [40]:
p=combinations(alpha,3)
list(p)

[('A', 'B', 'C'), ('A', 'B', 'D'), ('A', 'C', 'D'), ('B', 'C', 'D')]

In [41]:
num=[1,2,3]
p=combinations(num,2)
list(p)

[(1, 2), (1, 3), (2, 3)]

In [42]:
for c in combinations(num,2):
    if 2 in c:
        print(c)

(1, 2)
(2, 3)


In [43]:
for c in combinations(alpha,2):
    if 'A' in c:
        print(c)

('A', 'B')
('A', 'C')
('A', 'D')
